name: dart_basic
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  http: ^1.0.0
  intl: ^0.18.1
  string_validator: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
